# Generated by Django 6.1 on 2026-08-17 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_user_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='e.g. 10 for 10% off')),
                ('flat_discount', models.DecimalField(decimal_places=2, default=0, help_text='Flat Rs. off instead of percent (optional)', max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Gifting notes / personalization instructions from customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_photo',
            field=models.ImageField(blank=True, null=True, upload_to='personalizations/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_text',
            field=models.CharField(blank=True, help_text='Custom name/text requested by customer', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
    ]
