# Generated by Django 6.0.4 on 2026-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_discount_amount_and_more'),
    ]

    operations =[
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.CharField(max_length=..., unique=True, default=''),
         )
    
    ]  
