# Generated by Django 6.1 on 2026-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited total uses across all customers', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, help_text='How many times ONE customer/email may use this code'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
