# Generated by Django 5.0.6 on 2026-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_max_uses_coupon_max_uses_per_user_and_more'),
        ('orders', '0004_order_access_token'),
    ]

    operations = [
    ]
