# Generated by Django 5.0.6 on 2026-08-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20260822_2044'),
        ('orders', '0005_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
    ]
