# Generated by Django 5.0.6 on 2026-08-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20260823_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery/shipping charge (Rs.), 0 = free shipping', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST/tax amount (Rs.), if applicable', max_digits=10),
        ),
    ]
