# Generated by Django 5.0.6 on 2026-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_special_instructions_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Gifting notes / personalization instructions from customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='access_token',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
