# Generated by Django 6.1 on 2026-08-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='allow_personalization',
            field=models.BooleanField(default=True, help_text='Show custom text + photo upload fields on this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='audience_tag',
            field=models.CharField(blank=True, choices=[('', '— None —'), ('her', 'For Her'), ('him', 'For Him'), ('couple', 'For Couple'), ('newborn', 'For Newborn'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary')], help_text='Used for "Shop by Occasion" homepage tiles', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deal_of_day',
            field=models.BooleanField(default=False, help_text='Feature in the homepage Deal of the Day banner'),
        ),
    ]
