# Generated by Django 6.1 on 2026-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: link to a short unboxing/reaction video (YouTube/Instagram)'),
        ),
    ]
