# Generated by Django 6.1 on 2026-08-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_video_url'),
    ]

    operations = [
    ]