# Generated by Django 5.0.6 on 2026-08-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        ('products', '0005_productimage_productvariant_and_more'),
    ]

    operations = [
    ]
