# Generated by Django 5.0.6 on 2026-08-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20260829_2251'),
        ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g. S, M, L, XL (leave blank if not applicable)', max_length=50)),
                ('color', models.CharField(blank=True, help_text='e.g. Red, Blue (leave blank if not applicable)', max_length=50)),
                ('sku', models.CharField(blank=True, help_text='Optional unique code for this variant', max_length=64, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Full price for this specific variant (Rs.)', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['size', 'color'],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_variant_per_product'),
        ),
    ]
